spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework: INFO
    com.farmstock: INFO