spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000 # 60s
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000 # 5 minutes
      max-lifetime: 1200000 # 20 minutes
  mvc:
    async:
      request-timeout: 60000 # 60s
server:
  port: ${PORT:8080}
  tomcat:
    connection-timeout: 60s
    threads:
      max: 200
      min-spare: 10

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    org.hibernate: DEBUG
    com.farmstock: DEBUG
    org.springframework.web: DEBUG