spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  datasource:
    hikari:
      connection-timeout: 20000 # 20s
      maximum-pool-size: 5
  mvc:
    async:
      request-timeout: 30000 # 30s
server:
  port: ${PORT:8080}
  tomcat:
    connection-timeout: 30000

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: INFO
    org.hibernate: INFO